version: '3.8' 

services:  
  app: 
    image: php:8.2-apache 

    ports:  
      "8000:80"

    volumes:    
      - ./api:/var/www/html

    depends_on:  
      - db  
  db:  
    image: msql:8

    restart: always

    enviroments: 
      MSQL_ROOT_PASSWORD: root  
      MSQL_DATABASE: Clase
        
    ports: 
      - "3306:3306" 

    phpmyadmin: 
      image: phpmyadmin/phpmyadmin 
      ports:
        - "8080:80" 

      enviroment: 
        PMA_HOST: db  
        MSQL_ROOT_PASSWORD: root  
      depends_on:
        - db     

 